### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by NEXUS-Liu** [tsinghua-fib-lab/DRL-Rumor-Mitigation#1]
感谢您的分享，但是我在您的工作基础上进行复现，发现了以下问题，请问该如何解决？
Traceback (most recent call last):
  File "/root/anaconda3/envs/DGM4/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/root/anaconda3/envs/DGM4/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/rumor/DRL-Rumor-Mitigation-main/DRL-Rumor-Mitigation-main/news/train.py", line 15, in <module>
    from news.utils.config import Config
  File "/root/rumor/DRL-Rumor-Mitigation-main/DRL-Rumor-Mitigation-main/news/utils/config.py", line 2, in <module>
    from khrylib.utils import load_yaml
ModuleNotFoundError: No module named 'khrylib.utils'

**Comment by ran-dommm** [comment]
Thank you for your issue, we have added necessary files to run the code.
